// Generated by CIRCT firtool-1.62.0
// Standard header to adapt well known macros for register randomization.
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_

// Include register initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for prints and assertions.

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// VCS coverage exclude_file
module regfile_32x32(	// cpu_design/src/main/scala/cpu/Core.scala:18:20
  input  [4:0]  R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [4:0]  R1_addr,
  input         R1_en,
                R1_clk,
  output [31:0] R1_data,
  input  [4:0]  R2_addr,
  input         R2_en,
                R2_clk,
  output [31:0] R2_data,
  input  [4:0]  W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:31];	// cpu_design/src/main/scala/cpu/Core.scala:18:20
  always @(posedge W0_clk) begin	// cpu_design/src/main/scala/cpu/Core.scala:18:20
    if (W0_en & 1'h1)	// cpu_design/src/main/scala/cpu/Core.scala:18:20
      Memory[W0_addr] <= W0_data;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// cpu_design/src/main/scala/cpu/Core.scala:18:20
    reg [31:0] _RANDOM_MEM;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
    initial begin	// cpu_design/src/main/scala/cpu/Core.scala:18:20
      `INIT_RANDOM_PROLOG_	// cpu_design/src/main/scala/cpu/Core.scala:18:20
      `ifdef RANDOMIZE_MEM_INIT	// cpu_design/src/main/scala/cpu/Core.scala:18:20
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          _RANDOM_MEM = `RANDOM;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
          Memory[i[4:0]] = _RANDOM_MEM;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
        end	// cpu_design/src/main/scala/cpu/Core.scala:18:20
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
  assign R2_data = R2_en ? Memory[R2_addr] : 32'bx;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
endmodule

// VCS coverage exclude_file
module csr_regfile_4096x32(	// cpu_design/src/main/scala/cpu/Core.scala:19:24
  input  [11:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [31:0] R0_data,
  input  [11:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [31:0] R1_data,
  input  [11:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [31:0] W0_data
);

  reg [31:0] Memory[0:4095];	// cpu_design/src/main/scala/cpu/Core.scala:19:24
  always @(posedge W0_clk) begin	// cpu_design/src/main/scala/cpu/Core.scala:19:24
    if (W0_en & 1'h1)	// cpu_design/src/main/scala/cpu/Core.scala:19:24
      Memory[W0_addr] <= W0_data;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// cpu_design/src/main/scala/cpu/Core.scala:19:24
    reg [31:0] _RANDOM_MEM;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
    initial begin	// cpu_design/src/main/scala/cpu/Core.scala:19:24
      `INIT_RANDOM_PROLOG_	// cpu_design/src/main/scala/cpu/Core.scala:19:24
      `ifdef RANDOMIZE_MEM_INIT	// cpu_design/src/main/scala/cpu/Core.scala:19:24
        for (logic [12:0] i = 13'h0; i < 13'h1000; i += 13'h1) begin
          _RANDOM_MEM = `RANDOM;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
          Memory[i[11:0]] = _RANDOM_MEM;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
        end	// cpu_design/src/main/scala/cpu/Core.scala:19:24
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 32'bx;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
  assign R1_data = R1_en ? Memory[R1_addr] : 32'bx;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
endmodule

module Core(	// cpu_design/src/main/scala/cpu/Core.scala:8:7
  input         clock,	// cpu_design/src/main/scala/cpu/Core.scala:8:7
                reset,	// cpu_design/src/main/scala/cpu/Core.scala:8:7
  output [31:0] io_imem_addr,	// cpu_design/src/main/scala/cpu/Core.scala:9:14
  input  [31:0] io_imem_inst,	// cpu_design/src/main/scala/cpu/Core.scala:9:14
  output [31:0] io_dmem_addr,	// cpu_design/src/main/scala/cpu/Core.scala:9:14
  input  [31:0] io_dmem_rdata,	// cpu_design/src/main/scala/cpu/Core.scala:9:14
  output        io_dmem_wen,	// cpu_design/src/main/scala/cpu/Core.scala:9:14
  output [31:0] io_dmem_wdata,	// cpu_design/src/main/scala/cpu/Core.scala:9:14
                io_gp,	// cpu_design/src/main/scala/cpu/Core.scala:9:14
  output        io_exit	// cpu_design/src/main/scala/cpu/Core.scala:9:14
);

  wire [31:0]      mem_wb_data;	// src/main/scala/chisel3/util/Mux.scala:126:16
  wire             exe_jmp_flg;	// cpu_design/src/main/scala/cpu/Core.scala:254:34
  wire             exe_br_flg;	// src/main/scala/chisel3/util/Mux.scala:126:16
  wire [31:0]      _csr_regfile_ext_R0_data;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
  wire [31:0]      _csr_regfile_ext_R1_data;	// cpu_design/src/main/scala/cpu/Core.scala:19:24
  wire [31:0]      _regfile_ext_R1_data;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
  wire [31:0]      _regfile_ext_R2_data;	// cpu_design/src/main/scala/cpu/Core.scala:18:20
  reg  [31:0]      id_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:26:38
  reg  [31:0]      id_reg_inst;	// cpu_design/src/main/scala/cpu/Core.scala:27:38
  reg  [31:0]      exe_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:30:38
  reg  [4:0]       exe_reg_wb_addr;	// cpu_design/src/main/scala/cpu/Core.scala:31:38
  reg  [31:0]      exe_reg_op1_data;	// cpu_design/src/main/scala/cpu/Core.scala:32:38
  reg  [31:0]      exe_reg_op2_data;	// cpu_design/src/main/scala/cpu/Core.scala:33:38
  reg  [31:0]      exe_reg_rs2_data;	// cpu_design/src/main/scala/cpu/Core.scala:34:38
  reg  [4:0]       exe_reg_exe_fun;	// cpu_design/src/main/scala/cpu/Core.scala:35:38
  reg  [1:0]       exe_reg_mem_wen;	// cpu_design/src/main/scala/cpu/Core.scala:36:38
  reg  [1:0]       exe_reg_rf_wen;	// cpu_design/src/main/scala/cpu/Core.scala:37:38
  reg  [2:0]       exe_reg_wb_sel;	// cpu_design/src/main/scala/cpu/Core.scala:38:38
  reg  [11:0]      exe_reg_csr_addr;	// cpu_design/src/main/scala/cpu/Core.scala:39:38
  reg  [2:0]       exe_reg_csr_cmd;	// cpu_design/src/main/scala/cpu/Core.scala:40:38
  reg  [31:0]      exe_reg_imm_b_sext;	// cpu_design/src/main/scala/cpu/Core.scala:43:38
  reg  [31:0]      mem_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:48:38
  reg  [4:0]       mem_reg_wb_addr;	// cpu_design/src/main/scala/cpu/Core.scala:49:38
  reg  [31:0]      mem_reg_op1_data;	// cpu_design/src/main/scala/cpu/Core.scala:50:38
  reg  [31:0]      mem_reg_rs2_data;	// cpu_design/src/main/scala/cpu/Core.scala:51:38
  reg  [1:0]       mem_reg_mem_wen;	// cpu_design/src/main/scala/cpu/Core.scala:52:38
  reg  [1:0]       mem_reg_rf_wen;	// cpu_design/src/main/scala/cpu/Core.scala:53:38
  reg  [2:0]       mem_reg_wb_sel;	// cpu_design/src/main/scala/cpu/Core.scala:54:38
  reg  [11:0]      mem_reg_csr_addr;	// cpu_design/src/main/scala/cpu/Core.scala:55:38
  reg  [2:0]       mem_reg_csr_cmd;	// cpu_design/src/main/scala/cpu/Core.scala:56:38
  reg  [31:0]      mem_reg_alu_out;	// cpu_design/src/main/scala/cpu/Core.scala:58:38
  reg  [4:0]       wb_reg_wb_addr;	// cpu_design/src/main/scala/cpu/Core.scala:61:38
  reg  [1:0]       wb_reg_rf_wen;	// cpu_design/src/main/scala/cpu/Core.scala:62:38
  reg  [31:0]      wb_reg_wb_data;	// cpu_design/src/main/scala/cpu/Core.scala:63:38
  reg  [31:0]      if_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:69:26
  wire             _id_inst_T = exe_br_flg | exe_jmp_flg;	// cpu_design/src/main/scala/cpu/Core.scala:95:17, :254:34, src/main/scala/chisel3/util/Mux.scala:126:16
  wire             _id_rs2_data_hazard_T = exe_reg_rf_wen == 2'h1;	// cpu_design/src/main/scala/cpu/Core.scala:37:38, :108:44
  wire             stall_flg =
    _id_rs2_data_hazard_T & (|(id_reg_inst[19:15]))
    & id_reg_inst[19:15] == exe_reg_wb_addr | _id_rs2_data_hazard_T
    & (|(id_reg_inst[24:20])) & id_reg_inst[24:20] == exe_reg_wb_addr;	// cpu_design/src/main/scala/cpu/Core.scala:27:38, :31:38, :104:34, :105:34, :108:{44,73,82,100}, :109:{73,82,100}, :110:36
  wire [31:0]      id_inst = _id_inst_T | stall_flg ? 32'h13 : id_reg_inst;	// cpu_design/src/main/scala/cpu/Core.scala:27:38, :95:17, :110:36, :113:{20,48}, src/main/scala/chisel3/util/Mux.scala:126:16
  wire             _id_rs2_data_T_2 = mem_reg_rf_wen == 2'h1;	// cpu_design/src/main/scala/cpu/Core.scala:53:38, :108:44, :122:59
  wire             _id_rs2_data_T_5 = wb_reg_rf_wen == 2'h1;	// cpu_design/src/main/scala/cpu/Core.scala:62:38, :108:44, :123:59
  wire [31:0]      id_rs1_data =
    id_inst[19:15] == 5'h0
      ? 32'h0
      : id_inst[19:15] == mem_reg_wb_addr & _id_rs2_data_T_2
          ? mem_wb_data
          : id_inst[19:15] == wb_reg_wb_addr & _id_rs2_data_T_5
              ? wb_reg_wb_data
              : _regfile_ext_R2_data;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :18:20, :26:38, :49:38, :61:38, :63:38, :113:20, :115:28, :121:18, :122:{19,40,59}, :123:{19,40,59}, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [31:0]      id_rs2_data =
    id_inst[24:20] == 5'h0
      ? 32'h0
      : id_inst[24:20] == mem_reg_wb_addr & _id_rs2_data_T_2
          ? mem_wb_data
          : id_inst[24:20] == wb_reg_wb_addr & _id_rs2_data_T_5
              ? wb_reg_wb_data
              : _regfile_ext_R1_data;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :18:20, :26:38, :49:38, :61:38, :63:38, :113:20, :116:28, :122:59, :123:59, :126:18, :127:{19,40}, :128:{19,40}, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [31:0]      _exe_alu_out_T_31 = exe_reg_op1_data + exe_reg_op2_data;	// cpu_design/src/main/scala/cpu/Core.scala:32:38, :33:38, :229:58
  wire [62:0]      _exe_alu_out_T_14 = {31'h0, exe_reg_op1_data} << exe_reg_op2_data[4:0];	// cpu_design/src/main/scala/cpu/Core.scala:32:38, :33:38, :234:{58,77}
  wire [31:0]      _GEN = {27'h0, exe_reg_op2_data[4:0]};	// cpu_design/src/main/scala/cpu/Core.scala:33:38, :142:31, :234:77, :235:58
  wire             _exe_br_flg_T_17 = exe_reg_op1_data < exe_reg_op2_data;	// cpu_design/src/main/scala/cpu/Core.scala:32:38, :33:38, :238:58
  wire [31:0]      exe_alu_out =
    exe_reg_exe_fun == 5'h1
      ? _exe_alu_out_T_31
      : exe_reg_exe_fun == 5'h2
          ? exe_reg_op1_data - exe_reg_op2_data
          : exe_reg_exe_fun == 5'h3
              ? exe_reg_op1_data & exe_reg_op2_data
              : exe_reg_exe_fun == 5'h4
                  ? exe_reg_op1_data | exe_reg_op2_data
                  : exe_reg_exe_fun == 5'h5
                      ? exe_reg_op1_data ^ exe_reg_op2_data
                      : exe_reg_exe_fun == 5'h6
                          ? _exe_alu_out_T_14[31:0]
                          : exe_reg_exe_fun == 5'h7
                              ? exe_reg_op1_data >> _GEN
                              : exe_reg_exe_fun == 5'h8
                                  ? $signed($signed(exe_reg_op1_data) >>> _GEN)
                                  : exe_reg_exe_fun == 5'h9
                                      ? {31'h0,
                                         $signed(exe_reg_op1_data) < $signed(exe_reg_op2_data)}
                                      : exe_reg_exe_fun == 5'hA
                                          ? {31'h0, _exe_br_flg_T_17}
                                          : exe_reg_exe_fun == 5'h11
                                              ? _exe_alu_out_T_31 & 32'hFFFFFFFE
                                              : exe_reg_exe_fun == 5'h12
                                                  ? exe_reg_op1_data
                                                  : 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :26:38, :32:38, :33:38, :35:38, :229:{22,58}, :230:{22,58}, :231:{22,58}, :232:{22,58}, :233:{22,58}, :234:{22,58,84}, :235:{22,58}, :236:{22,65}, :237:{22,65}, :238:{22,58}, :239:{22,79,81}, :240:22, src/main/scala/chisel3/util/Mux.scala:126:16
  wire             _exe_br_flg_T_3 = exe_reg_op1_data == exe_reg_op2_data;	// cpu_design/src/main/scala/cpu/Core.scala:32:38, :33:38, :245:57
  assign exe_br_flg =
    exe_reg_exe_fun == 5'hB
      ? _exe_br_flg_T_3
      : exe_reg_exe_fun == 5'hC
          ? ~_exe_br_flg_T_3
          : exe_reg_exe_fun == 5'hD
              ? $signed(exe_reg_op1_data) < $signed(exe_reg_op2_data)
              : exe_reg_exe_fun == 5'hE
                  ? $signed(exe_reg_op1_data) >= $signed(exe_reg_op2_data)
                  : exe_reg_exe_fun == 5'hF
                      ? _exe_br_flg_T_17
                      : exe_reg_exe_fun == 5'h10 & ~_exe_br_flg_T_17;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :32:38, :33:38, :35:38, :238:58, :245:{22,57}, :246:{22,38}, :247:{22,64}, :248:{22,64}, :249:22, :250:{22,38}, src/main/scala/chisel3/util/Mux.scala:126:16
  assign exe_jmp_flg = exe_reg_wb_sel == 3'h2;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, :254:34, src/main/scala/chisel3/util/Lookup.scala:34:39
  assign mem_wb_data =
    mem_reg_wb_sel == 3'h1
      ? io_dmem_rdata
      : mem_reg_wb_sel == 3'h2
          ? mem_reg_pc + 32'h4
          : mem_reg_wb_sel == 3'h3 ? _csr_regfile_ext_R1_data : mem_reg_alu_out;	// cpu_design/src/main/scala/cpu/Core.scala:19:24, :48:38, :54:38, :58:38, :79:31, :294:21, :295:{21,48}, :296:21, src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/chisel3/util/Mux.scala:126:16
  `ifndef SYNTHESIS	// cpu_design/src/main/scala/cpu/Core.scala:320:9
    always @(posedge clock) begin	// cpu_design/src/main/scala/cpu/Core.scala:320:9
      if ((`PRINTF_COND_) & ~reset) begin	// cpu_design/src/main/scala/cpu/Core.scala:320:9, :334:9
        $fwrite(32'h80000002, "if_reg_pc        : 0x%x\n", if_reg_pc);	// cpu_design/src/main/scala/cpu/Core.scala:69:26, :320:9
        $fwrite(32'h80000002, "id_reg_pc        : 0x%x\n", id_reg_pc);	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :320:9, :321:9
        $fwrite(32'h80000002, "id_reg_inst      : 0x%x\n", id_reg_inst);	// cpu_design/src/main/scala/cpu/Core.scala:27:38, :320:9, :322:9
        $fwrite(32'h80000002, "stall_flg        : 0x%x\n", stall_flg);	// cpu_design/src/main/scala/cpu/Core.scala:110:36, :320:9, :323:9
        $fwrite(32'h80000002, "id_inst          : 0x%x\n", id_inst);	// cpu_design/src/main/scala/cpu/Core.scala:113:20, :320:9, :324:9
        $fwrite(32'h80000002, "id_rs1_data      : 0x%x\n", id_rs1_data);	// cpu_design/src/main/scala/cpu/Core.scala:320:9, :325:9, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "id_rs2_data      : 0x%x\n", id_rs2_data);	// cpu_design/src/main/scala/cpu/Core.scala:320:9, :326:9, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "exe_reg_pc       : 0x%x\n", exe_reg_pc);	// cpu_design/src/main/scala/cpu/Core.scala:30:38, :320:9, :327:9
        $fwrite(32'h80000002, "exe_reg_op1_data : 0x%x\n", exe_reg_op1_data);	// cpu_design/src/main/scala/cpu/Core.scala:32:38, :320:9, :328:9
        $fwrite(32'h80000002, "exe_reg_op2_data : 0x%x\n", exe_reg_op2_data);	// cpu_design/src/main/scala/cpu/Core.scala:33:38, :320:9, :329:9
        $fwrite(32'h80000002, "exe_alu_out      : 0x%x\n", exe_alu_out);	// cpu_design/src/main/scala/cpu/Core.scala:320:9, :330:9, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "mem_reg_pc       : 0x%x\n", mem_reg_pc);	// cpu_design/src/main/scala/cpu/Core.scala:48:38, :320:9, :331:9
        $fwrite(32'h80000002, "mem_wb_data      : 0x%x\n", mem_wb_data);	// cpu_design/src/main/scala/cpu/Core.scala:320:9, :332:9, src/main/scala/chisel3/util/Mux.scala:126:16
        $fwrite(32'h80000002, "wb_reg_wb_data   : 0x%x\n", wb_reg_wb_data);	// cpu_design/src/main/scala/cpu/Core.scala:63:38, :320:9, :333:9
        $fwrite(32'h80000002, "---------\n");	// cpu_design/src/main/scala/cpu/Core.scala:320:9, :334:9
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [9:0]       _GEN_0 = {id_inst[14:12], id_inst[6:0]};	// cpu_design/src/main/scala/cpu/Core.scala:113:20, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_1 = _GEN_0 == 10'h103;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_3 = _GEN_0 == 10'h123;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire [16:0]      _GEN_1 = {id_inst[31:25], id_inst[14:12], id_inst[6:0]};	// cpu_design/src/main/scala/cpu/Core.scala:113:20, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_5 = _GEN_1 == 17'h33;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_7 = _GEN_0 == 10'h13;	// src/main/scala/chisel3/util/Lookup.scala:31:38, src/main/scala/chisel3/util/Mux.scala:126:16
  wire             _csignals_T_9 = _GEN_1 == 17'h8033;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_11 = _GEN_1 == 17'h3B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_13 = _GEN_1 == 17'h333;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_15 = _GEN_1 == 17'h233;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_17 = _GEN_0 == 10'h393;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_19 = _GEN_0 == 10'h313;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_21 = _GEN_0 == 10'h213;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_23 = _GEN_1 == 17'hB3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_25 = _GEN_1 == 17'h2B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_27 = _GEN_1 == 17'h82B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_29 = _GEN_1 == 17'h93;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_31 = _GEN_1 == 17'h293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_33 = _GEN_1 == 17'h8293;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_35 = _GEN_1 == 17'h133;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_37 = _GEN_1 == 17'h1B3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_39 = _GEN_0 == 10'h113;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_41 = _GEN_0 == 10'h193;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_43 = _GEN_0 == 10'h63;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_45 = _GEN_0 == 10'hE3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_47 = _GEN_0 == 10'h2E3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_49 = _GEN_0 == 10'h3E3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_51 = _GEN_0 == 10'h263;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_53 = _GEN_0 == 10'h363;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_55 = id_inst[6:0] == 7'h6F;	// cpu_design/src/main/scala/cpu/Core.scala:113:20, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_57 = _GEN_0 == 10'h67;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_59 = id_inst[6:0] == 7'h37;	// cpu_design/src/main/scala/cpu/Core.scala:113:20, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_61 = id_inst[6:0] == 7'h17;	// cpu_design/src/main/scala/cpu/Core.scala:113:20, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_63 = _GEN_0 == 10'hF3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_65 = _GEN_0 == 10'h2F3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_67 = _GEN_0 == 10'h173;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_69 = _GEN_0 == 10'h373;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_71 = _GEN_0 == 10'h1F3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_73 = _GEN_0 == 10'h3F3;	// src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _csignals_T_75 = id_inst == 32'h73;	// cpu_design/src/main/scala/cpu/Core.scala:84:14, :113:20, src/main/scala/chisel3/util/Lookup.scala:31:38
  wire             _GEN_2 = _csignals_T_71 | _csignals_T_73;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_3 =
    _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _csignals_T_69 | _GEN_2;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_4 = _csignals_T_59 | _csignals_T_61;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_5 =
    _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51
    | _csignals_T_53;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_6 =
    _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9 | _csignals_T_11
    | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 | _csignals_T_19 | _csignals_T_21
    | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31
    | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41
    | _GEN_5;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire             _GEN_7 = _csignals_T_39 | _csignals_T_41;	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [2:0]       csignals_6 =
    _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9
    | _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 | _csignals_T_19
    | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29
    | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39
    | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49
    | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _GEN_4
      ? 3'h0
      : _csignals_T_63 | _csignals_T_65
          ? 3'h1
          : _csignals_T_67 | _csignals_T_69
              ? 3'h2
              : _GEN_2 ? 3'h3 : {_csignals_T_75, 2'h0};	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :38:38, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
  wire [3:0][31:0] _GEN_8 =
    {{{27'h0, id_inst[19:15]}}, {32'h0}, {id_reg_pc}, {id_rs1_data}};	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :113:20, :115:28, :142:{26,31}, :190:17, :191:17, :192:17, src/main/scala/chisel3/util/Mux.scala:126:16
  wire [7:0][31:0] _GEN_9 =
    {{32'h0},
     {32'h0},
     {{id_inst[31:12], 12'h0}},
     {{{12{id_inst[31]}}, id_inst[19:12], id_inst[20], id_inst[30:21], 1'h0}},
     {{{20{id_inst[31]}}, id_inst[31:25], id_inst[11:7]}},
     {{{20{id_inst[31]}}, id_inst[31:20]}},
     {id_rs2_data},
     {32'h0}};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :26:38, :39:38, :113:20, :117:28, :131:25, :132:{26,31,44}, :133:29, :134:{26,31,44}, :135:29, :137:{42,59,72}, :138:26, :139:25, :140:29, :195:17, :196:17, :197:17, :198:17, :199:17, src/main/scala/chisel3/util/Mux.scala:126:16
  always @(posedge clock) begin	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    if (reset) begin	// cpu_design/src/main/scala/cpu/Core.scala:8:7
      id_reg_pc <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38
      id_reg_inst <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :27:38
      exe_reg_pc <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :30:38
      exe_reg_wb_addr <= 5'h0;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :31:38
      exe_reg_op1_data <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :32:38
      exe_reg_op2_data <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :33:38
      exe_reg_rs2_data <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :34:38
      exe_reg_exe_fun <= 5'h0;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      exe_reg_mem_wen <= 2'h0;	// cpu_design/src/main/scala/cpu/Core.scala:36:38
      exe_reg_rf_wen <= 2'h0;	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :37:38
      exe_reg_wb_sel <= 3'h0;	// cpu_design/src/main/scala/cpu/Core.scala:38:38
      exe_reg_csr_addr <= 12'h0;	// cpu_design/src/main/scala/cpu/Core.scala:39:38
      exe_reg_csr_cmd <= 3'h0;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, :40:38
      exe_reg_imm_b_sext <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :43:38
      mem_reg_pc <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :48:38
      mem_reg_wb_addr <= 5'h0;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :49:38
      mem_reg_op1_data <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :50:38
      mem_reg_rs2_data <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :51:38
      mem_reg_mem_wen <= 2'h0;	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :52:38
      mem_reg_rf_wen <= 2'h0;	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :53:38
      mem_reg_wb_sel <= 3'h0;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, :54:38
      mem_reg_csr_addr <= 12'h0;	// cpu_design/src/main/scala/cpu/Core.scala:39:38, :55:38
      mem_reg_csr_cmd <= 3'h0;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, :56:38
      mem_reg_alu_out <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :58:38
      wb_reg_wb_addr <= 5'h0;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :61:38
      wb_reg_rf_wen <= 2'h0;	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :62:38
      wb_reg_wb_data <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :63:38
      if_reg_pc <= 32'h0;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :69:26
    end
    else begin	// cpu_design/src/main/scala/cpu/Core.scala:8:7
      if (~stall_flg)	// cpu_design/src/main/scala/cpu/Core.scala:110:36
        id_reg_pc <= if_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :69:26
      if (_id_inst_T)	// cpu_design/src/main/scala/cpu/Core.scala:95:17
        id_reg_inst <= 32'h13;	// cpu_design/src/main/scala/cpu/Core.scala:27:38, src/main/scala/chisel3/util/Mux.scala:126:16
      else if (~stall_flg)	// cpu_design/src/main/scala/cpu/Core.scala:110:36
        id_reg_inst <= io_imem_inst;	// cpu_design/src/main/scala/cpu/Core.scala:27:38
      exe_reg_pc <= id_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:26:38, :30:38
      exe_reg_wb_addr <= id_inst[11:7];	// cpu_design/src/main/scala/cpu/Core.scala:31:38, :113:20, :117:28
      exe_reg_op1_data <=
        _GEN_8[_csignals_T_1 | _GEN_6
                 ? 2'h0
                 : _csignals_T_55
                     ? 2'h1
                     : _csignals_T_57
                         ? 2'h0
                         : _csignals_T_59
                             ? 2'h2
                             : _csignals_T_61
                                 ? 2'h1
                                 : _csignals_T_63
                                     ? 2'h0
                                     : _csignals_T_65
                                         ? 2'h3
                                         : _csignals_T_67
                                             ? 2'h0
                                             : _csignals_T_69
                                                 ? 2'h3
                                                 : _csignals_T_71
                                                     ? 2'h0
                                                     : _csignals_T_73
                                                         ? 2'h3
                                                         : {_csignals_T_75, 1'h0}];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :32:38, :36:38, :108:44, :190:17, :191:17, :192:17, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/chisel3/util/Mux.scala:126:16
      exe_reg_op2_data <=
        _GEN_9[_csignals_T_1
                 ? 3'h2
                 : _csignals_T_3
                     ? 3'h3
                     : _csignals_T_5
                         ? 3'h1
                         : _csignals_T_7
                             ? 3'h2
                             : _csignals_T_9 | _csignals_T_11 | _csignals_T_13
                               | _csignals_T_15
                                 ? 3'h1
                                 : _csignals_T_17 | _csignals_T_19 | _csignals_T_21
                                     ? 3'h2
                                     : _csignals_T_23 | _csignals_T_25 | _csignals_T_27
                                         ? 3'h1
                                         : _csignals_T_29 | _csignals_T_31
                                           | _csignals_T_33
                                             ? 3'h2
                                             : _csignals_T_35 | _csignals_T_37
                                                 ? 3'h1
                                                 : _GEN_7
                                                     ? 3'h2
                                                     : _GEN_5
                                                         ? 3'h1
                                                         : _csignals_T_55
                                                             ? 3'h4
                                                             : _csignals_T_57
                                                                 ? 3'h2
                                                                 : _GEN_4
                                                                     ? 3'h5
                                                                     : {2'h0,
                                                                        ~(_csignals_T_63
                                                                          | _csignals_T_65
                                                                          | _csignals_T_67
                                                                          | _csignals_T_69
                                                                          | _csignals_T_71
                                                                          | _csignals_T_73
                                                                          | _csignals_T_75)}];	// cpu_design/src/main/scala/cpu/Core.scala:33:38, :36:38, :195:17, :196:17, :197:17, :198:17, :199:17, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39, src/main/scala/chisel3/util/Mux.scala:126:16
      exe_reg_rs2_data <= id_rs2_data;	// cpu_design/src/main/scala/cpu/Core.scala:34:38, src/main/scala/chisel3/util/Mux.scala:126:16
      if (_csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7)	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
        exe_reg_exe_fun <= 5'h1;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_9)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h2;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_11)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h3;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_13)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h4;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_15)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h5;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_17)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h3;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_19)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h4;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_21)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h5;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_23)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h6;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_25)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h7;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_27)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h8;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_29)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h6;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_31)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h7;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_33)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h8;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_35)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h9;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_37)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'hA;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_39)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h9;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_41)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'hA;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_43)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'hB;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_45)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'hC;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_47)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'hE;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_49)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h10;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_51)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'hD;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_53)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'hF;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_55)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h1;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_csignals_T_57)	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_exe_fun <= 5'h11;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_GEN_4)	// src/main/scala/chisel3/util/Lookup.scala:34:39
        exe_reg_exe_fun <= 5'h1;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else if (_GEN_3)	// src/main/scala/chisel3/util/Lookup.scala:34:39
        exe_reg_exe_fun <= 5'h12;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      else	// src/main/scala/chisel3/util/Lookup.scala:34:39
        exe_reg_exe_fun <= 5'h0;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :35:38
      exe_reg_mem_wen <= _csignals_T_1 ? 2'h0 : {1'h0, _csignals_T_3};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :36:38, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
      if (_csignals_T_1) begin	// src/main/scala/chisel3/util/Lookup.scala:31:38
        exe_reg_rf_wen <= 2'h1;	// cpu_design/src/main/scala/cpu/Core.scala:37:38, :108:44
        exe_reg_wb_sel <= 3'h1;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, src/main/scala/chisel3/util/Lookup.scala:34:39
      end
      else begin	// src/main/scala/chisel3/util/Lookup.scala:31:38
        if (_csignals_T_3)	// src/main/scala/chisel3/util/Lookup.scala:31:38
          exe_reg_rf_wen <= 2'h0;	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :37:38
        else if (_csignals_T_5 | _csignals_T_7 | _csignals_T_9 | _csignals_T_11
                 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 | _csignals_T_19
                 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27
                 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33 | _csignals_T_35
                 | _csignals_T_37 | _GEN_7)	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
          exe_reg_rf_wen <= 2'h1;	// cpu_design/src/main/scala/cpu/Core.scala:37:38, :108:44
        else if (_GEN_5)	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_rf_wen <= 2'h0;	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :37:38
        else	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_rf_wen <=
            {1'h0,
             _csignals_T_55 | _csignals_T_57 | _csignals_T_59 | _csignals_T_61 | _GEN_3};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :37:38, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
        if (_GEN_6)	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_wb_sel <= 3'h0;	// cpu_design/src/main/scala/cpu/Core.scala:38:38
        else if (_csignals_T_55 | _csignals_T_57)	// src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39
          exe_reg_wb_sel <= 3'h2;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, src/main/scala/chisel3/util/Lookup.scala:34:39
        else if (_GEN_4 | ~_GEN_3)	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_wb_sel <= 3'h0;	// cpu_design/src/main/scala/cpu/Core.scala:38:38
        else	// src/main/scala/chisel3/util/Lookup.scala:34:39
          exe_reg_wb_sel <= 3'h3;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, src/main/scala/chisel3/util/Lookup.scala:34:39
      end
      exe_reg_csr_addr <= csignals_6 == 3'h4 ? 12'h342 : id_inst[31:20];	// cpu_design/src/main/scala/cpu/Core.scala:39:38, :113:20, :131:25, :202:{24,36}, src/main/scala/chisel3/util/Lookup.scala:34:39
      exe_reg_csr_cmd <= csignals_6;	// cpu_design/src/main/scala/cpu/Core.scala:40:38, src/main/scala/chisel3/util/Lookup.scala:34:39
      exe_reg_imm_b_sext <=
        {{20{id_inst[31]}}, id_inst[7], id_inst[30:25], id_inst[11:8], 1'h0};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :43:38, :113:20, :135:{29,42,54,71}, :136:26
      mem_reg_pc <= exe_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:30:38, :48:38
      mem_reg_wb_addr <= exe_reg_wb_addr;	// cpu_design/src/main/scala/cpu/Core.scala:31:38, :49:38
      mem_reg_op1_data <= exe_reg_op1_data;	// cpu_design/src/main/scala/cpu/Core.scala:32:38, :50:38
      mem_reg_rs2_data <= exe_reg_rs2_data;	// cpu_design/src/main/scala/cpu/Core.scala:34:38, :51:38
      mem_reg_mem_wen <= exe_reg_mem_wen;	// cpu_design/src/main/scala/cpu/Core.scala:36:38, :52:38
      mem_reg_rf_wen <= exe_reg_rf_wen;	// cpu_design/src/main/scala/cpu/Core.scala:37:38, :53:38
      mem_reg_wb_sel <= exe_reg_wb_sel;	// cpu_design/src/main/scala/cpu/Core.scala:38:38, :54:38
      mem_reg_csr_addr <= exe_reg_csr_addr;	// cpu_design/src/main/scala/cpu/Core.scala:39:38, :55:38
      mem_reg_csr_cmd <= exe_reg_csr_cmd;	// cpu_design/src/main/scala/cpu/Core.scala:40:38, :56:38
      mem_reg_alu_out <= exe_alu_out;	// cpu_design/src/main/scala/cpu/Core.scala:58:38, src/main/scala/chisel3/util/Mux.scala:126:16
      wb_reg_wb_addr <= mem_reg_wb_addr;	// cpu_design/src/main/scala/cpu/Core.scala:49:38, :61:38
      wb_reg_rf_wen <= mem_reg_rf_wen;	// cpu_design/src/main/scala/cpu/Core.scala:53:38, :62:38
      wb_reg_wb_data <= mem_wb_data;	// cpu_design/src/main/scala/cpu/Core.scala:63:38, src/main/scala/chisel3/util/Mux.scala:126:16
      if (exe_br_flg)	// src/main/scala/chisel3/util/Mux.scala:126:16
        if_reg_pc <= exe_reg_pc + exe_reg_imm_b_sext;	// cpu_design/src/main/scala/cpu/Core.scala:30:38, :43:38, :69:26, :252:31
      else if (exe_jmp_flg)	// cpu_design/src/main/scala/cpu/Core.scala:254:34
        if_reg_pc <= exe_alu_out;	// cpu_design/src/main/scala/cpu/Core.scala:69:26, src/main/scala/chisel3/util/Mux.scala:126:16
      else if (io_imem_inst == 32'h73)	// cpu_design/src/main/scala/cpu/Core.scala:84:14
        if_reg_pc <= _csr_regfile_ext_R0_data;	// cpu_design/src/main/scala/cpu/Core.scala:19:24, :69:26
      else if (~stall_flg)	// cpu_design/src/main/scala/cpu/Core.scala:110:36
        if_reg_pc <= if_reg_pc + 32'h4;	// cpu_design/src/main/scala/cpu/Core.scala:69:26, :79:31
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    `ifdef FIRRTL_BEFORE_INITIAL	// cpu_design/src/main/scala/cpu/Core.scala:8:7
      `FIRRTL_BEFORE_INITIAL	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:20];	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    initial begin	// cpu_design/src/main/scala/cpu/Core.scala:8:7
      `ifdef INIT_RANDOM_PROLOG_	// cpu_design/src/main/scala/cpu/Core.scala:8:7
        `INIT_RANDOM_PROLOG_	// cpu_design/src/main/scala/cpu/Core.scala:8:7
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// cpu_design/src/main/scala/cpu/Core.scala:8:7
        for (logic [4:0] i = 5'h0; i < 5'h15; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// cpu_design/src/main/scala/cpu/Core.scala:8:7
        end	// cpu_design/src/main/scala/cpu/Core.scala:8:7
        id_reg_pc = _RANDOM[5'h0];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :26:38
        id_reg_inst = _RANDOM[5'h1];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :27:38
        exe_reg_pc = _RANDOM[5'h2];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :30:38
        exe_reg_wb_addr = _RANDOM[5'h3][4:0];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :31:38
        exe_reg_op1_data = {_RANDOM[5'h3][31:5], _RANDOM[5'h4][4:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :31:38, :32:38
        exe_reg_op2_data = {_RANDOM[5'h4][31:5], _RANDOM[5'h5][4:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :32:38, :33:38
        exe_reg_rs2_data = {_RANDOM[5'h5][31:5], _RANDOM[5'h6][4:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :33:38, :34:38
        exe_reg_exe_fun = _RANDOM[5'h6][9:5];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :34:38, :35:38
        exe_reg_mem_wen = _RANDOM[5'h6][11:10];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :34:38, :36:38
        exe_reg_rf_wen = _RANDOM[5'h6][13:12];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :34:38, :37:38
        exe_reg_wb_sel = _RANDOM[5'h6][16:14];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :34:38, :38:38
        exe_reg_csr_addr = _RANDOM[5'h6][28:17];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :34:38, :39:38
        exe_reg_csr_cmd = _RANDOM[5'h6][31:29];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :34:38, :40:38
        exe_reg_imm_b_sext = _RANDOM[5'h9];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :43:38
        mem_reg_pc = _RANDOM[5'hC];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :48:38
        mem_reg_wb_addr = _RANDOM[5'hD][4:0];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :49:38
        mem_reg_op1_data = {_RANDOM[5'hD][31:5], _RANDOM[5'hE][4:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :49:38, :50:38
        mem_reg_rs2_data = {_RANDOM[5'hE][31:5], _RANDOM[5'hF][4:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :50:38, :51:38
        mem_reg_mem_wen = _RANDOM[5'hF][6:5];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :51:38, :52:38
        mem_reg_rf_wen = _RANDOM[5'hF][8:7];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :51:38, :53:38
        mem_reg_wb_sel = _RANDOM[5'hF][11:9];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :51:38, :54:38
        mem_reg_csr_addr = _RANDOM[5'hF][23:12];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :51:38, :55:38
        mem_reg_csr_cmd = _RANDOM[5'hF][26:24];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :51:38, :56:38
        mem_reg_alu_out = {_RANDOM[5'h10][31:27], _RANDOM[5'h11][26:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :58:38
        wb_reg_wb_addr = _RANDOM[5'h11][31:27];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :58:38, :61:38
        wb_reg_rf_wen = _RANDOM[5'h12][1:0];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :62:38
        wb_reg_wb_data = {_RANDOM[5'h12][31:2], _RANDOM[5'h13][1:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :62:38, :63:38
        if_reg_pc = {_RANDOM[5'h13][31:2], _RANDOM[5'h14][1:0]};	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :63:38, :69:26
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// cpu_design/src/main/scala/cpu/Core.scala:8:7
      `FIRRTL_AFTER_INITIAL	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  regfile_32x32 regfile_ext (	// cpu_design/src/main/scala/cpu/Core.scala:18:20
    .R0_addr (5'h3),	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    .R0_en   (1'h1),	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    .R0_clk  (clock),
    .R0_data (io_gp),
    .R1_addr (id_inst[24:20]),	// cpu_design/src/main/scala/cpu/Core.scala:113:20, :116:28
    .R1_en   (1'h1),	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    .R1_clk  (clock),
    .R1_data (_regfile_ext_R1_data),
    .R2_addr (id_inst[19:15]),	// cpu_design/src/main/scala/cpu/Core.scala:113:20, :115:28
    .R2_en   (1'h1),	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    .R2_clk  (clock),
    .R2_data (_regfile_ext_R2_data),
    .W0_addr (wb_reg_wb_addr),	// cpu_design/src/main/scala/cpu/Core.scala:61:38
    .W0_en   (_id_rs2_data_T_5),	// cpu_design/src/main/scala/cpu/Core.scala:123:59
    .W0_clk  (clock),
    .W0_data (wb_reg_wb_data)	// cpu_design/src/main/scala/cpu/Core.scala:63:38
  );
  csr_regfile_4096x32 csr_regfile_ext (	// cpu_design/src/main/scala/cpu/Core.scala:19:24
    .R0_addr (12'h305),	// cpu_design/src/main/scala/cpu/Core.scala:84:39
    .R0_en   (1'h1),	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    .R0_clk  (clock),
    .R0_data (_csr_regfile_ext_R0_data),
    .R1_addr (mem_reg_csr_addr),	// cpu_design/src/main/scala/cpu/Core.scala:55:38
    .R1_en   (1'h1),	// cpu_design/src/main/scala/cpu/Core.scala:8:7
    .R1_clk  (clock),
    .R1_data (_csr_regfile_ext_R1_data),
    .W0_addr (mem_reg_csr_addr),	// cpu_design/src/main/scala/cpu/Core.scala:55:38
    .W0_en   (|mem_reg_csr_cmd),	// cpu_design/src/main/scala/cpu/Core.scala:56:38, :289:24
    .W0_clk  (clock),
    .W0_data
      (mem_reg_csr_cmd == 3'h1
         ? mem_reg_op1_data
         : mem_reg_csr_cmd == 3'h2
             ? _csr_regfile_ext_R1_data | mem_reg_op1_data
             : mem_reg_csr_cmd == 3'h3
                 ? _csr_regfile_ext_R1_data & ~mem_reg_op1_data
                 : mem_reg_csr_cmd == 3'h4 ? 32'hB : 32'h0)	// cpu_design/src/main/scala/cpu/Core.scala:19:24, :26:38, :50:38, :56:38, :283:22, :284:{22,47}, :285:{22,47,49}, :286:22, src/main/scala/chisel3/util/Lookup.scala:34:39, src/main/scala/chisel3/util/Mux.scala:126:16
  );
  assign io_imem_addr = if_reg_pc;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :69:26
  assign io_dmem_addr = mem_reg_alu_out;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :58:38
  assign io_dmem_wen = mem_reg_mem_wen[0];	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :52:38, :276:17
  assign io_dmem_wdata = mem_reg_rs2_data;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :51:38
  assign io_exit = id_reg_inst == 32'hC0001073;	// cpu_design/src/main/scala/cpu/Core.scala:8:7, :27:38, :319:27
endmodule

// VCS coverage exclude_file
module mem_16384x8(	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  input  [13:0] R0_addr,
  input         R0_en,
                R0_clk,
  output [7:0]  R0_data,
  input  [13:0] R1_addr,
  input         R1_en,
                R1_clk,
  output [7:0]  R1_data,
  input  [13:0] R2_addr,
  input         R2_en,
                R2_clk,
  output [7:0]  R2_data,
  input  [13:0] R3_addr,
  input         R3_en,
                R3_clk,
  output [7:0]  R3_data,
  input  [13:0] R4_addr,
  input         R4_en,
                R4_clk,
  output [7:0]  R4_data,
  input  [13:0] R5_addr,
  input         R5_en,
                R5_clk,
  output [7:0]  R5_data,
  input  [13:0] R6_addr,
  input         R6_en,
                R6_clk,
  output [7:0]  R6_data,
  input  [13:0] R7_addr,
  input         R7_en,
                R7_clk,
  output [7:0]  R7_data,
  input  [13:0] W0_addr,
  input         W0_en,
                W0_clk,
  input  [7:0]  W0_data,
  input  [13:0] W1_addr,
  input         W1_en,
                W1_clk,
  input  [7:0]  W1_data,
  input  [13:0] W2_addr,
  input         W2_en,
                W2_clk,
  input  [7:0]  W2_data,
  input  [13:0] W3_addr,
  input         W3_en,
                W3_clk,
  input  [7:0]  W3_data
);

  reg [7:0] Memory[0:16383];	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  always @(posedge W0_clk) begin	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    if (W0_en & 1'h1)	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
      Memory[W0_addr] <= W0_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    if (W1_en & 1'h1)	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
      Memory[W1_addr] <= W1_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    if (W2_en & 1'h1)	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
      Memory[W2_addr] <= W2_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    if (W3_en & 1'h1)	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
      Memory[W3_addr] <= W3_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    reg [31:0] _RANDOM_MEM;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    initial begin	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
      `INIT_RANDOM_PROLOG_	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
      `ifdef RANDOMIZE_MEM_INIT	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
        for (logic [14:0] i = 15'h0; i < 15'h4000; i += 15'h1) begin
          _RANDOM_MEM = `RANDOM;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
          Memory[i[13:0]] = _RANDOM_MEM[7:0];	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
        end	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  assign R1_data = R1_en ? Memory[R1_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  assign R2_data = R2_en ? Memory[R2_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  assign R3_data = R3_en ? Memory[R3_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  assign R4_data = R4_en ? Memory[R4_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  assign R5_data = R5_en ? Memory[R5_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  assign R6_data = R6_en ? Memory[R6_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  assign R7_data = R7_en ? Memory[R7_addr] : 8'bx;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
endmodule

module Memory(	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
  input         clock,	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
  input  [31:0] io_imem_addr,	// cpu_design/src/main/scala/cpu/Memory.scala:21:14
  output [31:0] io_imem_inst,	// cpu_design/src/main/scala/cpu/Memory.scala:21:14
  input  [31:0] io_dmem_addr,	// cpu_design/src/main/scala/cpu/Memory.scala:21:14
  output [31:0] io_dmem_rdata,	// cpu_design/src/main/scala/cpu/Memory.scala:21:14
  input         io_dmem_wen,	// cpu_design/src/main/scala/cpu/Memory.scala:21:14
  input  [31:0] io_dmem_wdata	// cpu_design/src/main/scala/cpu/Memory.scala:21:14
);

  wire [7:0]  _mem_ext_R0_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [7:0]  _mem_ext_R1_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [7:0]  _mem_ext_R2_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [7:0]  _mem_ext_R3_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [7:0]  _mem_ext_R4_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [7:0]  _mem_ext_R5_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [7:0]  _mem_ext_R6_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [7:0]  _mem_ext_R7_data;	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  wire [13:0] _io_dmem_rdata_T = io_dmem_addr[13:0] + 14'h3;	// cpu_design/src/main/scala/cpu/Memory.scala:29:22, :35:22
  wire [13:0] _io_dmem_rdata_T_3 = io_dmem_addr[13:0] + 14'h2;	// cpu_design/src/main/scala/cpu/Memory.scala:30:22, :35:22, :36:22
  wire [13:0] _io_dmem_rdata_T_6 = io_dmem_addr[13:0] + 14'h1;	// cpu_design/src/main/scala/cpu/Memory.scala:31:22, :35:22, :37:22
  mem_16384x8 mem_ext (	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    .R0_addr (io_imem_addr[13:0]),	// cpu_design/src/main/scala/cpu/Memory.scala:32:8
    .R0_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .R1_addr (io_imem_addr[13:0] + 14'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:29:22, :31:22
    .R1_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R1_clk  (clock),
    .R1_data (_mem_ext_R1_data),
    .R2_addr (io_imem_addr[13:0] + 14'h2),	// cpu_design/src/main/scala/cpu/Memory.scala:29:22, :30:22
    .R2_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R2_clk  (clock),
    .R2_data (_mem_ext_R2_data),
    .R3_addr (io_imem_addr[13:0] + 14'h3),	// cpu_design/src/main/scala/cpu/Memory.scala:29:22
    .R3_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R3_clk  (clock),
    .R3_data (_mem_ext_R3_data),
    .R4_addr (io_dmem_addr[13:0]),	// cpu_design/src/main/scala/cpu/Memory.scala:38:8
    .R4_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R4_clk  (clock),
    .R4_data (_mem_ext_R4_data),
    .R5_addr (_io_dmem_rdata_T_6),	// cpu_design/src/main/scala/cpu/Memory.scala:37:22
    .R5_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R5_clk  (clock),
    .R5_data (_mem_ext_R5_data),
    .R6_addr (_io_dmem_rdata_T_3),	// cpu_design/src/main/scala/cpu/Memory.scala:36:22
    .R6_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R6_clk  (clock),
    .R6_data (_mem_ext_R6_data),
    .R7_addr (_io_dmem_rdata_T),	// cpu_design/src/main/scala/cpu/Memory.scala:35:22
    .R7_en   (1'h1),	// cpu_design/src/main/scala/cpu/Memory.scala:20:7
    .R7_clk  (clock),
    .R7_data (_mem_ext_R7_data),
    .W0_addr (_io_dmem_rdata_T),	// cpu_design/src/main/scala/cpu/Memory.scala:35:22
    .W0_en   (io_dmem_wen),
    .W0_clk  (clock),
    .W0_data (io_dmem_wdata[31:24]),	// cpu_design/src/main/scala/cpu/Memory.scala:45:57
    .W1_addr (_io_dmem_rdata_T_3),	// cpu_design/src/main/scala/cpu/Memory.scala:36:22
    .W1_en   (io_dmem_wen),
    .W1_clk  (clock),
    .W1_data (io_dmem_wdata[23:16]),	// cpu_design/src/main/scala/cpu/Memory.scala:44:57
    .W2_addr (_io_dmem_rdata_T_6),	// cpu_design/src/main/scala/cpu/Memory.scala:37:22
    .W2_en   (io_dmem_wen),
    .W2_clk  (clock),
    .W2_data (io_dmem_wdata[15:8]),	// cpu_design/src/main/scala/cpu/Memory.scala:43:57
    .W3_addr (io_dmem_addr[13:0]),	// cpu_design/src/main/scala/cpu/Memory.scala:38:8
    .W3_en   (io_dmem_wen),
    .W3_clk  (clock),
    .W3_data (io_dmem_wdata[7:0])	// cpu_design/src/main/scala/cpu/Memory.scala:42:57
  );
  assign io_imem_inst =
    {_mem_ext_R3_data, _mem_ext_R2_data, _mem_ext_R1_data, _mem_ext_R0_data};	// cpu_design/src/main/scala/cpu/Memory.scala:20:7, :26:16, :28:22
  assign io_dmem_rdata =
    {_mem_ext_R7_data, _mem_ext_R6_data, _mem_ext_R5_data, _mem_ext_R4_data};	// cpu_design/src/main/scala/cpu/Memory.scala:20:7, :26:16, :34:23
endmodule

module Top(	// cpu_design/src/main/scala/cpu/Top.scala:7:7
  input         clock,	// cpu_design/src/main/scala/cpu/Top.scala:7:7
                reset,	// cpu_design/src/main/scala/cpu/Top.scala:7:7
  output [31:0] io_gp,	// cpu_design/src/main/scala/cpu/Top.scala:8:14
  output        io_exit	// cpu_design/src/main/scala/cpu/Top.scala:8:14
);

  wire [31:0] _memory_io_imem_inst;	// cpu_design/src/main/scala/cpu/Top.scala:13:22
  wire [31:0] _memory_io_dmem_rdata;	// cpu_design/src/main/scala/cpu/Top.scala:13:22
  wire [31:0] _core_io_imem_addr;	// cpu_design/src/main/scala/cpu/Top.scala:12:20
  wire [31:0] _core_io_dmem_addr;	// cpu_design/src/main/scala/cpu/Top.scala:12:20
  wire        _core_io_dmem_wen;	// cpu_design/src/main/scala/cpu/Top.scala:12:20
  wire [31:0] _core_io_dmem_wdata;	// cpu_design/src/main/scala/cpu/Top.scala:12:20
  Core core (	// cpu_design/src/main/scala/cpu/Top.scala:12:20
    .clock         (clock),
    .reset         (reset),
    .io_imem_addr  (_core_io_imem_addr),
    .io_imem_inst  (_memory_io_imem_inst),	// cpu_design/src/main/scala/cpu/Top.scala:13:22
    .io_dmem_addr  (_core_io_dmem_addr),
    .io_dmem_rdata (_memory_io_dmem_rdata),	// cpu_design/src/main/scala/cpu/Top.scala:13:22
    .io_dmem_wen   (_core_io_dmem_wen),
    .io_dmem_wdata (_core_io_dmem_wdata),
    .io_gp         (io_gp),
    .io_exit       (io_exit)
  );
  Memory memory (	// cpu_design/src/main/scala/cpu/Top.scala:13:22
    .clock         (clock),
    .io_imem_addr  (_core_io_imem_addr),	// cpu_design/src/main/scala/cpu/Top.scala:12:20
    .io_imem_inst  (_memory_io_imem_inst),
    .io_dmem_addr  (_core_io_dmem_addr),	// cpu_design/src/main/scala/cpu/Top.scala:12:20
    .io_dmem_rdata (_memory_io_dmem_rdata),
    .io_dmem_wen   (_core_io_dmem_wen),	// cpu_design/src/main/scala/cpu/Top.scala:12:20
    .io_dmem_wdata (_core_io_dmem_wdata)	// cpu_design/src/main/scala/cpu/Top.scala:12:20
  );
endmodule


// ----- 8< ----- FILE "mem_16384x8_init.sv" ----- 8< -----

// Generated by CIRCT firtool-1.62.0
module mem_16384x8_init();	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
  initial	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
    $readmemh("src/hex/hazard_ex.hex", mem_16384x8.Memory);	// cpu_design/src/main/scala/cpu/Memory.scala:26:16
endmodule

bind mem_16384x8 mem_16384x8_init mem_16384x8_init ();
